keycloak.server-url=http://localhost:8080
keycloak.realm=genuino
keycloak.admin.realm=master
keycloak.admin.username=admin
keycloak.admin.password=admin

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB