keycloak.server-url=http://localhost:8080
keycloak.realm=genuino
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB